### ISSUE TITLE
Issue with font sizing on Windows 10

### ISSUE THREAD

**Issue by JD21P** [LCARSx32/Main-LCARS-x32-Project#12]
All the font sizing for all buttons are too big and all button words are cut off.
It happens on older versions from 0.6.4 to latest 0.7.2 so it must be a Windows 10 thing.
Here is a screenshot:
https://imgur.com/aEJwcYx

Is there a way to fix this?
Also how's the project going, is it still in development?
Thanks :-)

**Comment by Surak256** [comment]
You don't have the LCARS font installed, so it's defaulted to a sans-serif font that's wider. The file you need to install is lcars.ttf in the .zip distribution. If you used an installer that's supposed to install it automatically you may need to restart your computer for it to register correctly or install it manually. Let me know how this goes.

Development has been stalled for a while; I've been very busy with a degree and then a full-time job, but I haven't forgotten about this. The last issue I ran into was some changes in the Windows 10 window manager that I couldn't get to work consistently across versions. (#9)

**Comment by JD21P** [comment]
Ah yes! I found and installed the LCARS font and it is now using the correct font, Thank you. :-)

With the amount of version changes with Windows 10 I assume it would be difficult to keep up, unless not much gets changed?

I am supprised and love how well the custom voice commands work, the voice command section alone would make a great separate application. :-)

**Comment by Surak256** [comment]
I'm glad you're problem's fixed. Thanks for the complement on the voice commands; I put a lot of work into them.

The problem with Windows 10 wasn't that there were frequent updates, so much as that the updates changed fundamental things like the windowing system. Figuring out what the new way to implement something is and making it work on previous versions of Windows too was a substantial time sink.
