### ISSUE TITLE
Error and CTD when opening Settings

### ISSUE THREAD

**Issue by TK-313** [LCARSx32/Main-LCARS-x32-Project#7]
This is what happens when I try to open the settings (incremental build 0.7.2, Windows 10). Screenshot and log file attached.
![2018-03-09_13-23-36](https://user-images.githubusercontent.com/26329719/37203027-66908fce-239d-11e8-9e37-be04e8724caf.png)
[LCARSError.txt](https://github.com/LCARSx32/Main-LCARS-x32-Project/files/1796470/LCARSError.txt)

**Comment by Surak256** [comment]
First, thanks for giving me both a screenshot and log file. This made this much easier to track down.

Second, it appears that I didn't take into account some languages using a comma as a decimal separator, so the default value of "5.0" isn't parsing. I'll update this issue when I've gone through the rest of that module for any similar bugs.

Quick fix: Rename this file as a .reg and install it to update the problematic value.
[DblFix.txt](https://github.com/LCARSx32/Main-LCARS-x32-Project/files/1797113/DblFix.txt)

**Comment by Surak256** [comment]
Fixed with revision 7b8e908429029462814f4b587ffcd2c408f07280. This will go out with the next release.
